import Foundation

enum ShellScriptFactory {
    static func makeSceneScript(_ configuration: InstallConfiguration) -> String {
        let settings = configuration.customization
        let pets = configuration.pets.isEmpty ? [PetLibrary.pets[0]] : configuration.pets
        let openers = configuration.openers.isEmpty
            ? [TerminalOpener(id: "silent", text: "", mood: .dry, isCustom: false)]
            : configuration.openers

        let petCases = makePetCases(pets)
        let openerArguments = openers.map { opener in
            shellQuote(oneLine(opener.text))
        }.joined(separator: " \\\n          ")
        let guardCommands = makeGuardCommands(settings)
        let metadataCommands = makeMetadataCommands(settings)
        let titleCommands = makeTitleCommands(settings)
        let effectCommands = makeEffectCommands(settings)
        let divider = shellQuote(oneLine(settings.dividerStyle.glyphs))
        let colorMode = shellQuote(settings.petColorMode.rawValue.lowercased())
        let showName = configuration.showPetName ? "1" : "0"
        let bell = settings.terminalBell ? "printf '\\a'" : ":"
        let respectNoColor = settings.respectNoColor ? "1" : "0"

        return """
        #!/bin/sh
        # Generated by Terminal Pet 0.2. Edit in the app, then choose Install / Update.

        [ -t 1 ] || exit 0
        [ "${TERM:-}" = "dumb" ] && exit 0

        tp_seed=${RANDOM:-$(/bin/date +%s)}
        \(guardCommands)

        tp_pet_count='\(pets.count)'
        tp_pet_pick=$((tp_seed % tp_pet_count + 1))
        case "$tp_pet_pick" in
        \(petCases)
        esac

        set -- \\
          \(openerArguments)
        tp_opener_count=$#
        tp_opener_pick=$(((tp_seed + 17) % tp_opener_count + 1))
        tp_i=1
        tp_line=''
        for tp_candidate do
          if [ "$tp_i" -eq "$tp_opener_pick" ]; then
            tp_line=$tp_candidate
            break
          fi
          tp_i=$((tp_i + 1))
        done

        tp_replace() {
          tp_value=$1
          tp_needle=$2
          tp_replacement=$3
          tp_result=''
          while :; do
            case "$tp_value" in
              *"$tp_needle"*)
                tp_prefix=${tp_value%%"$tp_needle"*}
                tp_result=$tp_result$tp_prefix$tp_replacement
                tp_value=${tp_value#*"$tp_needle"}
                ;;
              *)
                printf '%s' "$tp_result$tp_value"
                return
                ;;
            esac
          done
        }

        tp_user=${USER:-human}
        tp_host=$(hostname -s 2>/dev/null || hostname 2>/dev/null || printf 'this-machine')
        tp_cwd=${PWD:-somewhere}
        case "$tp_cwd" in
          "$HOME"*) tp_cwd="~${tp_cwd#"$HOME"}" ;;
        esac
        tp_shell_name=${SHELL##*/}
        tp_line=$(tp_replace "$tp_line" '{user}' "$tp_user")
        tp_line=$(tp_replace "$tp_line" '{host}' "$tp_host")
        tp_line=$(tp_replace "$tp_line" '{cwd}' "$tp_cwd")
        tp_line=$(tp_replace "$tp_line" '{pet}' "$tp_name")

        tp_primary='\(configuration.tint.ansiCode)'
        tp_secondary='\(settings.secondaryTint.ansiCode)'
        tp_opener_color='\(settings.openerTint.ansiCode)'
        tp_meta_color='\(settings.metadataTint.ansiCode)'
        tp_color_mode=\(colorMode)
        tp_use_color=1
        if [ '\(respectNoColor)' = '1' ] && [ -n "${NO_COLOR+x}" ]; then tp_use_color=0; fi

        tp_print_color() {
          if [ "$tp_use_color" -eq 1 ]; then
            printf '\\033[38;5;%sm%s\\033[0m' "$1" "$2"
          else
            printf '%s' "$2"
          fi
        }

        tp_color_for_line() {
          case "$tp_color_mode" in
            duotone)
              if [ $(( $1 % 2 )) -eq 0 ]; then printf '%s' "$tp_primary"; else printf '%s' "$tp_secondary"; fi
              ;;
            rainbow)
              case $(( $1 % 8 )) in
                0) printf '203' ;; 1) printf '209' ;; 2) printf '221' ;; 3) printf '119' ;;
                4) printf '45' ;; 5) printf '75' ;; 6) printf '141' ;; *) printf '213' ;;
              esac
              ;;
            *) printf '%s' "$tp_primary" ;;
          esac
        }

        tp_render_art() {
          tp_render_delay=$1
          tp_render_index=0
          printf '%s\\n' "$tp_art" | while IFS= read -r tp_art_line; do
            tp_render_color=$(tp_color_for_line "$tp_render_index")
            tp_print_color "$tp_render_color" "$tp_art_line"
            printf '\\n'
            if [ "$tp_render_delay" != '0' ]; then /bin/sleep "$tp_render_delay"; fi
            tp_render_index=$((tp_render_index + 1))
          done
        }

        tp_meta=''
        tp_add_meta() {
          [ -z "$1" ] && return
          if [ -z "$tp_meta" ]; then tp_meta=$1; else tp_meta="$tp_meta  ·  $1"; fi
        }
        \(metadataCommands)

        \(titleCommands)

        printf '\\n'
        \(effectCommands)

        tp_divider=\(divider)
        if [ -n "$tp_divider" ]; then
          tp_print_color "$tp_secondary" "$tp_divider"
          printf '\\n'
        fi

        if [ '\(showName)' = '1' ]; then
          if [ "$tp_use_color" -eq 1 ]; then printf '\\033[1;38;5;%sm%s\\033[0m' "$tp_primary" "$tp_name"; else printf '%s' "$tp_name"; fi
          if [ -n "$tp_line" ]; then
            printf '  '
            tp_print_color "$tp_opener_color" "$tp_line"
          fi
          printf '\\n'
        elif [ -n "$tp_line" ]; then
          tp_print_color "$tp_opener_color" "$tp_line"
          printf '\\n'
        fi

        if [ -n "$tp_meta" ]; then
          tp_print_color "$tp_meta_color" "$tp_meta"
          printf '\\n'
        fi
        \(bell)
        printf '\\n'
        """ + "\n"
    }

    static func makeZshPrompt(_ configuration: InstallConfiguration) -> String {
        let prompt = configuration.customization.prompt
        let primary = prompt.primaryTint.ansiCode
        let secondary = prompt.secondaryTint.ansiCode
        let symbol = shellQuote(safePromptSymbol(prompt.symbol))
        let timePart = prompt.showTime ? "tp_parts+=(\"%F{\(secondary)}%D{%H:%M}%f\")" : ":"
        let userPart = prompt.showUserHost ? "tp_parts+=(\"%F{\(primary)}%n@%m%f\")" : ":"
        let cwdPart = prompt.showCWD ? "tp_parts+=(\"%F{\(secondary)}%~%f\")" : ":"
        let gitPart = prompt.showGitBranch
            ? "tp_branch=$(_terminal_pet_git_branch); [[ -n \"$tp_branch\" ]] && tp_parts+=(\"%F{\(primary)}git:$tp_branch%f\")"
            : ":"
        let statusPart = prompt.showExitStatus
            ? "(( tp_last != 0 )) && tp_parts+=(\"%F{203}✕ $tp_last%f\")"
            : ":"
        let reaction = prompt.errorReactions ? zshReaction(secondary: secondary) : ":"
        let style = zshPromptStyle(prompt.style, primary: primary)

        return """
        # Generated by Terminal Pet. Sourced by zsh.
        _terminal_pet_git_branch() {
          command git symbolic-ref --quiet --short HEAD 2>/dev/null || command git rev-parse --short HEAD 2>/dev/null
        }

        _terminal_pet_precmd() {
          local tp_last=$?
          local tp_branch=''
          local tp_joined=''
          local -a tp_parts
          tp_parts=()
          \(timePart)
          \(userPart)
          \(cwdPart)
          \(gitPart)
          \(statusPart)
          tp_joined="${(j: · :)tp_parts}"
          local tp_symbol=\(symbol)
          \(reaction)
          \(style)
        }

        autoload -Uz add-zsh-hook
        add-zsh-hook -d precmd _terminal_pet_precmd 2>/dev/null
        add-zsh-hook precmd _terminal_pet_precmd
        """ + "\n"
    }

    static func makeBashPrompt(_ configuration: InstallConfiguration) -> String {
        let prompt = configuration.customization.prompt
        let primary = prompt.primaryTint.ansiCode
        let secondary = prompt.secondaryTint.ansiCode
        let symbol = shellQuote(safePromptSymbol(prompt.symbol))
        let timePart = prompt.showTime ? "tp_parts+=(\"${tp_secondary}\\A${tp_reset}\")" : ":"
        let userPart = prompt.showUserHost ? "tp_parts+=(\"${tp_primary}\\u@\\h${tp_reset}\")" : ":"
        let cwdPart = prompt.showCWD ? "tp_parts+=(\"${tp_secondary}\\w${tp_reset}\")" : ":"
        let gitPart = prompt.showGitBranch
            ? "tp_branch=$(_terminal_pet_git_branch); [ -n \"$tp_branch\" ] && tp_parts+=(\"${tp_primary}git:$tp_branch${tp_reset}\")"
            : ":"
        let statusPart = prompt.showExitStatus
            ? "[ \"$tp_last\" -ne 0 ] && tp_parts+=(\"${tp_error}✕ $tp_last${tp_reset}\")"
            : ":"
        let reaction = prompt.errorReactions ? bashReaction(secondary: secondary) : ":"
        let style = bashPromptStyle(prompt.style)

        return """
        # Generated by Terminal Pet. Sourced by Bash.
        _terminal_pet_git_branch() {
          command git symbolic-ref --quiet --short HEAD 2>/dev/null || command git rev-parse --short HEAD 2>/dev/null
        }

        terminal_pet_prompt_command() {
          local tp_last=$?
          local tp_primary='\\[\\033[38;5;\(primary)m\\]'
          local tp_secondary='\\[\\033[38;5;\(secondary)m\\]'
          local tp_error='\\[\\033[38;5;203m\\]'
          local tp_reset='\\[\\033[0m\\]'
          local tp_symbol=\(symbol)
          local tp_branch=''
          local tp_joined=''
          local tp_item=''
          local tp_parts=()
          \(timePart)
          \(userPart)
          \(cwdPart)
          \(gitPart)
          \(statusPart)
          for tp_item in "${tp_parts[@]}"; do
            if [ -z "$tp_joined" ]; then tp_joined=$tp_item; else tp_joined="$tp_joined · $tp_item"; fi
          done
          \(reaction)
          \(style)
        }

        case ";${PROMPT_COMMAND:-};" in
          *";terminal_pet_prompt_command;"*) ;;
          *) PROMPT_COMMAND="terminal_pet_prompt_command${PROMPT_COMMAND:+;$PROMPT_COMMAND}" ;;
        esac
        """ + "\n"
    }

    private static func makePetCases(_ pets: [TerminalPet]) -> String {
        var cases: [String] = []
        for (index, pet) in pets.enumerated() {
            let name = shellQuote(oneLine(pet.name))
            let art = shellQuote(sanitize(pet.art))
            cases.append("""
              \(index + 1))
                tp_name=\(name)
                tp_art=\(art)
                ;;
            """)
        }
        return cases.joined(separator: "\n")
    }

    private static func makeGuardCommands(_ settings: CustomizationSettings) -> String {
        var commands: [String] = []
        switch settings.sessionScope {
        case .everywhere: break
        case .localOnly: commands.append("[ -n \"${SSH_CONNECTION:-}${SSH_TTY:-}\" ] && exit 0")
        case .sshOnly: commands.append("[ -z \"${SSH_CONNECTION:-}${SSH_TTY:-}\" ] && exit 0")
        }
        if settings.skipIDETerminals {
            commands.append("case \"${TERM_PROGRAM:-}\" in vscode|JetBrains-JediTerm) exit 0 ;; esac")
        }
        if settings.quietHoursEnabled {
            let start = max(0, min(23, settings.quietStart))
            let end = max(0, min(23, settings.quietEnd))
            commands.append("tp_hour=$(/bin/date +%H); tp_hour=${tp_hour#0}; [ -n \"$tp_hour\" ] || tp_hour=0")
            if start < end {
                commands.append("[ \"$tp_hour\" -ge '\(start)' ] && [ \"$tp_hour\" -lt '\(end)' ] && exit 0")
            } else if start > end {
                commands.append("{ [ \"$tp_hour\" -ge '\(start)' ] || [ \"$tp_hour\" -lt '\(end)' ]; } && exit 0")
            }
        }
        switch settings.frequency {
        case .everyShell:
            break
        case .oncePerTerminal:
            commands.append("""
            tp_session_raw=${TERM_SESSION_ID:-${ITERM_SESSION_ID:-$$}}
            tp_session_key=$(printf '%s' "$tp_session_raw" | /usr/bin/tr -cd '[:alnum:]_-')
            tp_session_stamp="$HOME/.terminal-pet/session-${tp_session_key:-$$}"
            [ -f "$tp_session_stamp" ] && exit 0
            : > "$tp_session_stamp"
            """)
        case .oncePerDay:
            commands.append("""
            tp_today=$(/bin/date +%Y-%m-%d)
            tp_day_stamp="$HOME/.terminal-pet/last-shown-day"
            [ -f "$tp_day_stamp" ] && [ "$(/bin/cat "$tp_day_stamp" 2>/dev/null)" = "$tp_today" ] && exit 0
            printf '%s' "$tp_today" > "$tp_day_stamp"
            """)
        case .coinFlip:
            commands.append("[ $((tp_seed % 2)) -ne 0 ] && exit 0")
        }
        return commands.isEmpty ? ":" : commands.joined(separator: "\n")
    }

    private static func makeMetadataCommands(_ settings: CustomizationSettings) -> String {
        var commands: [String] = []
        if settings.showClock { commands.append("tp_add_meta \"$(/bin/date '+%H:%M')\"") }
        if settings.showDate { commands.append("tp_add_meta \"$(/bin/date '+%a, %b %d')\"") }
        if settings.showUserHost { commands.append("tp_add_meta \"$tp_user@$tp_host\"") }
        if settings.showCWD { commands.append("tp_add_meta \"$tp_cwd\"") }
        if settings.showOS {
            commands.append("tp_os=$(/usr/bin/sw_vers -productVersion 2>/dev/null); [ -n \"$tp_os\" ] && tp_add_meta \"macOS $tp_os\"")
        }
        if settings.showArchitecture { commands.append("tp_add_meta \"$(/usr/bin/uname -m)\"") }
        if settings.showShell { commands.append("tp_add_meta \"$tp_shell_name\"") }
        if settings.showBattery {
            commands.append("tp_battery=$(/usr/bin/pmset -g batt 2>/dev/null | /usr/bin/grep -o '[0-9][0-9]*%' | /usr/bin/head -1); [ -n \"$tp_battery\" ] && tp_add_meta \"battery $tp_battery\"")
        }
        if settings.showUptime {
            commands.append("tp_uptime=$(/usr/bin/uptime | /usr/bin/sed -E 's/^.* up +([^,]+),.*$/\\1/'); [ -n \"$tp_uptime\" ] && tp_add_meta \"up $tp_uptime\"")
        }
        if settings.showGitBranch {
            commands.append("tp_git=$(command git symbolic-ref --quiet --short HEAD 2>/dev/null || command git rev-parse --short HEAD 2>/dev/null); [ -n \"$tp_git\" ] && tp_add_meta \"git:$tp_git\"")
        }
        return commands.isEmpty ? ":" : commands.joined(separator: "\n")
    }

    private static func makeTitleCommands(_ settings: CustomizationSettings) -> String {
        guard settings.setWindowTitle else { return ":" }
        let title = shellQuote(oneLine(settings.windowTitle))
        return """
        tp_title=\(title)
        tp_title=$(tp_replace "$tp_title" '{user}' "$tp_user")
        tp_title=$(tp_replace "$tp_title" '{host}' "$tp_host")
        tp_title=$(tp_replace "$tp_title" '{cwd}' "$tp_cwd")
        tp_title=$(tp_replace "$tp_title" '{pet}' "$tp_name")
        printf '\\033]0;%s\\007' "$tp_title"
        """
    }

    private static func makeEffectCommands(_ settings: CustomizationSettings) -> String {
        let delay = settings.introSpeed.delay
        switch settings.introEffect {
        case .instant:
            return "tp_render_art '0'"
        case .lineReveal:
            return "tp_render_art '\(delay)'"
        case .ghostFlicker:
            return """
            tp_art_height=$(printf '%s\\n' "$tp_art" | /usr/bin/wc -l | /usr/bin/tr -d ' ')
            if [ "$tp_use_color" -eq 1 ]; then printf '\\033[2;38;5;%sm%s\\033[0m\\n' "$tp_secondary" "$tp_art"; else printf '%s\\n' "$tp_art"; fi
            /bin/sleep '\(delay)'
            printf '\\033[%sA\\033[J' "$tp_art_height"
            if [ "$tp_use_color" -eq 1 ]; then printf '\\033[38;5;%sm%s\\033[0m\\n' "$tp_secondary" "$tp_art"; else printf '%s\\n' "$tp_art"; fi
            /bin/sleep '\(delay)'
            printf '\\033[%sA\\033[J' "$tp_art_height"
            tp_render_art '0'
            """
        case .bootSequence:
            return """
            tp_print_color "$tp_meta_color" '[ terminal pet // waking ]'
            /bin/sleep '\(delay)'
            printf '\\r\\033[2K'
            tp_print_color "$tp_secondary" '[ familiar selected // link stable ]'
            /bin/sleep '\(delay)'
            printf '\\r\\033[2K'
            tp_render_art '0'
            """
        case .signalLock:
            return """
            tp_print_color "$tp_secondary" '· · · searching for creature signal'
            /bin/sleep '\(delay)'
            printf '\\r\\033[2K'
            tp_print_color "$tp_primary" '✦ signal locked'
            /bin/sleep '\(delay)'
            printf '\\r\\033[2K'
            tp_render_art '0'
            """
        }
    }

    private static func zshPromptStyle(_ style: PromptStyle, primary: Int) -> String {
        switch style {
        case .minimal:
            return "PROMPT=\"${tp_joined}${tp_joined:+  }%B%F{\(primary)}${tp_symbol}%f%b \""
        case .twoLine:
            return "PROMPT=\"${tp_joined}\"$'\\n'\"%B%F{\(primary)}${tp_symbol}%f%b \""
        case .capsule:
            return "PROMPT=\"%F{\(primary)}╭─[%f${tp_joined}%F{\(primary)}]%f\"$'\\n'\"%F{\(primary)}╰─%f%B${tp_symbol}%b \""
        case .operatorStyle:
            return "PROMPT=\"%F{\(primary)}┌ SYSTEM // %f${tp_joined}\"$'\\n'\"%F{\(primary)}└─ %B${tp_symbol}%b%f \""
        }
    }

    private static func bashPromptStyle(_ style: PromptStyle) -> String {
        switch style {
        case .minimal:
            return "PS1=\"${tp_joined}${tp_joined:+  }${tp_primary}${tp_symbol}${tp_reset} \""
        case .twoLine:
            return "PS1=\"${tp_joined}\\n${tp_primary}${tp_symbol}${tp_reset} \""
        case .capsule:
            return "PS1=\"${tp_primary}╭─[${tp_reset}${tp_joined}${tp_primary}]${tp_reset}\\n${tp_primary}╰─${tp_reset}${tp_symbol} \""
        case .operatorStyle:
            return "PS1=\"${tp_primary}┌ SYSTEM // ${tp_reset}${tp_joined}\\n${tp_primary}└─ ${tp_symbol}${tp_reset} \""
        }
    }

    private static func zshReaction(secondary: Int) -> String {
        """
        if (( tp_last != 0 )); then
          case $((RANDOM % 4)) in
            0) print -P "%F{\(secondary)}Your pet: bold strategy. The exit code disagrees.%f" ;;
            1) print -P "%F{\(secondary)}The creature has logged this betrayal.%f" ;;
            2) print -P "%F{\(secondary)}No judgment. Some judgment. Exit $tp_last.%f" ;;
            *) print -P "%F{\(secondary)}Tiny paws are now reviewing the stack trace.%f" ;;
          esac
        fi
        """
    }

    private static func bashReaction(secondary: Int) -> String {
        """
        if [ "$tp_last" -ne 0 ]; then
          case $((RANDOM % 4)) in
            0) printf '\\033[38;5;\(secondary)m%s\\033[0m\\n' 'Your pet: bold strategy. The exit code disagrees.' ;;
            1) printf '\\033[38;5;\(secondary)m%s\\033[0m\\n' 'The creature has logged this betrayal.' ;;
            2) printf '\\033[38;5;\(secondary)mNo judgment. Some judgment. Exit %s.\\033[0m\\n' "$tp_last" ;;
            *) printf '\\033[38;5;\(secondary)m%s\\033[0m\\n' 'Tiny paws are now reviewing the stack trace.' ;;
          esac
        fi
        """
    }

    private static func safePromptSymbol(_ value: String) -> String {
        let forbidden = CharacterSet(charactersIn: "$`\\%")
        var clean = ""
        for scalar in sanitize(oneLine(value)).unicodeScalars where !forbidden.contains(scalar) {
            clean.unicodeScalars.append(scalar)
        }
        clean = clean.trimmingCharacters(in: .whitespaces)
        return clean.isEmpty ? "❯" : String(clean.prefix(4))
    }

    private static func oneLine(_ value: String) -> String {
        sanitize(value).replacingOccurrences(of: "\n", with: " ")
    }

    private static func sanitize(_ value: String) -> String {
        var result = ""
        for scalar in value.unicodeScalars {
            if !CharacterSet.controlCharacters.contains(scalar) || scalar.value == 10 || scalar.value == 9 {
                result.unicodeScalars.append(scalar)
            }
        }
        return result
    }

    private static func shellQuote(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\"'\"'") + "'"
    }
}
